export const RESTART = 'RESTART';
export const SET_MEMORY = 'SET_MEMORY';
export const SET_NUMBER = 'SET_NUMBER';
export const RESET_NUMPAD = 'RESET_NUMPAD';
export const SEND_USER_CHOICE = 'SEND_USER_CHOICE';
export const INIT_MULTIPLICATIONS = 'INIT_MULTIPLICATIONS';